# Makefile additions for drag forces on dust grains
# [/source/Particles/ParticlesForces/shortRange/drag]

Particles += pt_yieldIntgrlData.o pt_yieldInit.o pt_sputYieldVel.o \
	     pt_sputRate.o pt_chargeData.o pt_chargeInit.o pt_grain_pot.o
